import type { Metadata } from "next"
import { Gowun_Dodum, Inter, Noto_Serif_KR } from "next/font/google"

import "./globals.css"

import Script from "next/script"

import { cn } from "@/lib/utils"

declare global {
  interface Window {
    naver: any
  }
}

const inter = Inter({ subsets: ["latin"] })
const notoSerif = Noto_Serif_KR({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "900"],
  variable: "--noto_serif_kr",
})

const gowunDodum = Gowun_Dodum({
  subsets: ["latin"],
  weight: "400",
  variable: "--gowun_dodum",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ko">
      <head>
        <Script
          strategy="beforeInteractive"
          src={`https://openapi.map.naver.com/openapi/v3/maps.js?ncpClientId=${process.env.NAVER_CLIENT_ID}`}
        ></Script>
      </head>
      <body className={cn("w-full", inter.className, notoSerif.variable, gowunDodum.variable)}>
        {children}
      </body>
    </html>
  )
}
